title: "Receitas Anna e Dawson"
email: 
description: "Guardando nossas receitas milenares"
twitter_username: "@dawsonfi"
github_username: "dawsonfi"
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Dawson Freitas Israel"
  avatar : "https://avatars2.githubusercontent.com/u/5369412?s=460&u=a0c84e2f0a693af386528bf7305d974accdea24e&v=4"
  bio    : "Cozinheiros de final de semana"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://dawsonfi.github.io/cooking"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/dawsonfi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dawsonfi"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/dawsonfi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dawsonfi"

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

defaults:
  # _recipes
  - scope:
      path: ""
      type: recipes
    values:
      layout: single
      tag_archive_path: /tags/
      category_archive_path: /categories/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
